import os
import telebot
import google.generativeai as genai

# DATA LOGIN JARVIS (AUTO-START AKTIF)
TELEGRAM_TOKEN = "8237850543:AAGhbmzaTt4bYV6SFnQ4GEmCRN5VYx5jzTc"
GEMINI_KEY = "AIzaSyDQ29GupI81bB-uZYNcU1rRAzCJJ2cTii0"
META_TOKEN = "eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI5MzdlNTQxNzkyZjcxNTA4ZTVkYzBjMmM1ZWUzOWFkMCIsImFjY2Vzc1J1bGVzIjpbeyJpZCI6InRyYWRpbmctYWNjb3VudC1tYW5hZ2VtZW50LWFwaSIsIm1ldGhvZHMiOlsidHJhZGluZy1hY2NvdW50LW1hbmFnZW1lbnQtYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6Im1ldGFhcGktcmVzdC1hcGkiLCJtZXRob2RzIjpbIm1ldGFhcGktYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6Im1ldGFhcGktcnBjLWFwaSIsIm1ldGhvZHMiOlsibWV0YWFwaS1hcGk6d3M6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6Im1ldGFhcGktcmVhbC10aW1lLXN0cmVhbWluZy1hcGkiLCJtZXRob2RzIjpbIm1ldGFhcGktYXBpOndzOnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIiwid3JpdGVyIl0sInJlc291cmNlcyI6WyIqOiRVU0VSX0lEJDoqIl19LHsiaWQiOiJtZXRhc3RhdHMtYXBpIiwibWV0aG9kcyI6WyJtZXRhc3RhdHMtYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6InJpc2stbWFuYWdlbWVudC1hcGkiLCJtZXRob2RzIjpbInJpc2stbWFuYWdlbWVudC1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciIsIndyaXRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfSx7ImlkIjoiY29weWZhY3RvcnktYXBpIiwibWV0aG9kcyI6WyJjb3B5ZmFjdG9yeS1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciIsIndyaXRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfSx7ImlkIjoibXQtbWFuYWdlci1hcGkiLCJtZXRob2RzIjpbIm10LW1hbmFnZXItYXBpOnJlc3Q6zGVhbGluZzoqOioiLCJtdC1tYW5hZ2VyLWFwaTpyZXN0OnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIiwid3JpdGVyIl0sInJlc291cmNlcyI6WyIqOiRVU0VSX0lEJDoqIl19LHsiaWQiOiJiaWxsaW5nLWFwaSIsIm1ldGhvZHMiOlsiYmlsbGluZy1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfV0sImlnbm9yZVJhdGVMaW1pdHMiOmZhbHNlLCJ0b2tlbklkIjoiMjAyMTAyMTMiLCJpbXBlcnNvbmF0ZWQiOmZhbHNlLCJyZWFsVXNlcklkIjoiOTM3ZTU0MTc5MmY3MTUwOGU1ZGMwYzJjNWVlMzlhZDAiLCJpYXQiOjE3NzA5Njc1ODd9.I8lWGvyQYmQEyOpjXp22KIk4HnyQXF7d0AwYtajU7AK_mW4w-IAOsCgVZX91g9POxKdFawvRUqekSXdnvsHshQ8mmsi2MUjHMV6xRICVPFyXXMGGUV6Ytt9PEOqhV3SSAjRs9v4kh6_PDXvv0K_tiyjWuhIMALvPNH0Ysp6LHbUL38AQNVHU_SVuONgC7_qVhEfA4IhL_BHc4yi0XYOYQuupiVetCt-IcAl3ap-Bp5ibocq7NzlzJrt136VbWQezYqjPwR972lqU42tXmWb-NBjLIF9Y0AVIk5ECOOLogvv01WCOXCuiEnV0hizMsqTjW5lCu3kwcLwSQpkD-HjwrmkvVleBwQ2OV9rEF8EpXw4fxM1hMQDab-ecZMIQBI_XSDa5fD_MoKR1DEmya-m7nM8_p1FLN8hzReTX4IVVw_Ia_GRdOFjZirUeBFocFAaAZoKA1LRpkipYD4Rti4FWh9V7cm1IqBYkJXnYwHUH5Hhch9OIvw7RgXkGQzAPjhNStq6Ymcw34eSDQPp76vCrA3o_enJzRHhkOfvmQzdOeJLZs9zh4bNZc5mzxchdhm1656H-GGUz8nIkhVI7wJDcPp0WsX3GGf-EDBBtW7JMcTE01SVATAwINQdwpg-jiNTUmPyH0krGJxCT409ud4zXMkbBRs6HmKxkHMmwt6n87ww"

bot = telebot.TeleBot(TELEGRAM_TOKEN)

@bot.message_handler(commands=['start'])
def welcome(message):
    bot.reply_to(message, "Jarvis Aktif & Berhasil Diinstal! Berburu gajian 1200 cent (Rp200.000) dimulai.")

@bot.message_handler(commands=['cek'])
def check(message):
    bot.reply_to(message, "Koneksi Aman. Server GitHub sedang memantau akun Valetax kamu.")

if __name__ == "__main__":
    print("Bot sedang berjalan...")
    bot.polling()
