name: Jalankan Jarvis
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *' # Otomatis restart tiap 6 jam agar tidak mati

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install alat
        run: pip install -r requirements.txt
      - name: Running Bot
        run: python bot.py
